name: try running dbt-cloud-action

on:
  workflow_dispatch:

concurrency: PROD

jobs:
  dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: kingalban/dbt-cloud-action@node16-to-node20
        id: dbt_cloud_run
        with:
          dbt_cloud_token: ${{ secrets.DBT_CLOUD_API_TOKEN }}
          dbt_cloud_account_id: ${{ vars.DBT_CLOUD_ACCOUNT_ID }}
          dbt_cloud_job_id: ${{ vars.DBT_CLOUD_JOB_ID__DEPLOY_PROD }}
          failure_on_error: true
          git_branch: main
          steps_override: |
            - echo hello world
